const viewer=document.querySelector('#product-viewer'),selection=document.querySelector('#selection'),notice=document.querySelector('#notice');
const state={size:'180',storage:'drawers-right',desktop:'glass',metal:'black',chair:'black'};
const names={'drawers-right':'Drawers right','drawers-left':'Drawers left','metal-legs':'Metal legs',glass:'Original black glass',walnut:'Walnut',oak:'Natural oak',black:'Black',white:'White',chrome:'Chrome',cognac:'Cognac',olive:'Olive',sand:'Sand'};
const presets={desktop:{glass:[[.1098,.1098,.1098,.7216],.5,.5,'BLEND'],walnut:[[.28,.11,.035,1],.36,0,'OPAQUE'],oak:[[.58,.34,.14,1],.42,0,'OPAQUE'],black:[[.025,.025,.025,1],.38,0,'OPAQUE'],white:[[.82,.77,.64,1],.48,0,'OPAQUE']},metal:{black:[[.018,.022,.026,1],.26,.88],white:[[.76,.76,.73,1],.32,.55],chrome:[[.72,.75,.78,1],.14,1]},chair:{black:[[.025,.028,.03,1],.5,0],cognac:[[.34,.13,.055,1],.43,0],olive:[[.11,.14,.075,1],.52,0],sand:[[.58,.48,.34,1],.56,0]}};
const materialNames={desktop:['*5'],metal:['[Color_008]1','[0131_Silver]','HMI- Polished Al1'],chair:['HMI- 3P14 (Vinyl1']};
function active(selector,current){document.querySelectorAll(selector).forEach(b=>{const on=b===current;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});}
function updateSummary(){selection.textContent=`${state.size} cm · ${names[state.storage]} · ${names[state.desktop]}`;}
function modelPath(){return `model/desk-${state.size}-${state.storage}.glb`;}
function applyMaterial(group){const p=presets[group][state[group]];if(!p||!viewer.model)return;for(const name of materialNames[group]){const m=[...viewer.model.materials].find(x=>x.name===name);if(!m)continue;const x=m.pbrMetallicRoughness;x.setBaseColorFactor(p[0]);x.setRoughnessFactor(p[1]);x.setMetallicFactor(p[2]);if(group==='desktop'&&p[3])m.setAlphaMode(p[3]);}viewer.requestUpdate?.();}
function applyAll(){Object.keys(materialNames).forEach(applyMaterial);updateSummary();notice.textContent='';}
viewer.addEventListener('load',applyAll);viewer.addEventListener('progress',e=>{const bar=viewer.querySelector('.progress'),span=bar?.querySelector('span');if(bar)bar.hidden=false;if(span)span.style.width=`${e.detail.totalProgress*100}%`;if(e.detail.totalProgress===1&&bar)bar.hidden=true;});
document.querySelectorAll('[data-model-group]').forEach(b=>b.addEventListener('click',()=>{const g=b.dataset.modelGroup;state[g]=b.dataset.value;active(`[data-model-group="${g}"]`,b);notice.textContent='Updating configuration…';viewer.src=modelPath();updateSummary();}));
document.querySelectorAll('[data-material]').forEach(b=>b.addEventListener('click',()=>{const g=b.dataset.material;state[g]=b.dataset.value;active(`[data-material="${g}"]`,b);applyMaterial(g);updateSummary();}));
document.querySelector('[data-action="rotate"]').addEventListener('click',e=>{const on=!viewer.hasAttribute('auto-rotate');viewer.toggleAttribute('auto-rotate',on);e.currentTarget.textContent=on?'Stop':'Rotate';e.currentTarget.setAttribute('aria-pressed',on)});
document.querySelector('[data-action="reset"]').addEventListener('click',()=>{viewer.cameraOrbit='35deg 66deg auto';viewer.cameraTarget='auto auto auto';viewer.fieldOfView='auto';viewer.jumpCameraToGoal?.()});
document.querySelector('[data-action="zoom-in"]').addEventListener('click',()=>{const o=viewer.getCameraOrbit();viewer.cameraOrbit=`${o.theta}rad ${o.phi}rad ${Math.max(o.radius*.82,.2)}m`});document.querySelector('[data-action="zoom-out"]').addEventListener('click',()=>{const o=viewer.getCameraOrbit();viewer.cameraOrbit=`${o.theta}rad ${o.phi}rad ${o.radius*1.2}m`});
document.querySelector('#add').addEventListener('click',()=>notice.textContent=`Added: Executive Desk — ${selection.textContent}`);document.querySelector('#print').addEventListener('click',()=>window.print());
