import {createViewer} from './three-viewer.js';

const page=document.body.dataset.product;
const viewer=createViewer(document.querySelector('#product-viewer'));
const ui={groups:document.querySelector('#material-groups'),details:document.querySelector('#material-details'),selection:document.querySelector('#selection'),notice:document.querySelector('#notice'),wheel:document.querySelector('#material-wheel'),wheelOptions:document.querySelector('#wheel-options')};
const asset=(path)=>new URL(path,import.meta.url).href;

const leather=[
  {id:'black-matte',label:'Siyah · Mat',image:asset('sofa/assets/black.webp'),roughness:.82},
  {id:'black-glossy',label:'Siyah · Parlak',image:asset('sofa/assets/black.webp'),roughness:.18},
  {id:'brown-matte',label:'Koyu Kahverengi · Mat',image:asset('sofa/assets/brown.webp'),roughness:.82},
  {id:'brown-glossy',label:'Koyu Kahverengi · Parlak',image:asset('sofa/assets/brown.webp'),roughness:.18},
  {id:'burgundy-matte',label:'Bordo · Mat',image:asset('sofa/assets/burgundy.webp'),roughness:.82},
  {id:'burgundy-glossy',label:'Bordo · Parlak',image:asset('sofa/assets/burgundy.webp'),roughness:.18},
];
const wood=[
  {id:'original',label:'Mevcut Ahşap',original:true,color:'#966f50'},
  ...[['oak-imbir','Meşe · Imbir'],['oak-nefrit','Meşe · Nefrit'],['oak-qvarz','Meşe · Qvarz'],['oak-marrakesh','Meşe · Marrakesh'],['oak-muskat','Meşe · Muskat'],['walnut-american','Amerikan Ceviz']].map(([id,label])=>({id,label,image:asset(`textures/wood/${id}.webp`),roughness:.5})),
];
const solids=[
  {id:'white',label:'Düz Beyaz · Yarı Mat',color:'#eeeae1',factor:[.86,.84,.8],roughness:.38},
  {id:'anthracite',label:'Antrasit · Yarı Mat',color:'#34383d',factor:[.035,.041,.048],roughness:.38},
];
const metal=[
  {id:'black',label:'Siyah Boyalı · Mat',color:'#171a1e',factor:[.018,.022,.027],metalness:.35,roughness:.78},
  {id:'white',label:'Beyaz Boyalı · Mat',color:'#ecebe7',factor:[.84,.83,.79],metalness:.18,roughness:.78},
  {id:'bronze',label:'Bronz · Yarı Parlak',color:'#8d6949',factor:[.33,.19,.095],metalness:1,roughness:.32},
  {id:'gold',label:'Altın · Yarı Parlak',color:'#c9a34b',factor:[.73,.48,.13],metalness:1,roughness:.3},
  {id:'chrome',label:'Krom · Parlak',color:'#dce4e8',factor:[.78,.84,.88],metalness:1,roughness:.07},
  {id:'chrome-matte',label:'Krom · Mat',color:'#bec5c8',factor:[.58,.63,.65],metalness:1,roughness:.46},
];
const glass=[
  {id:'smoked-black',label:'Siyah Füme Cam',color:'#1b2027',factor:[.02,.025,.035],metalness:.05,roughness:.3,glass:true,opacity:.68},
  {id:'frosted-clear',label:'Şeffaf Buzlu Cam',color:'#d9e1e3',factor:[.62,.72,.74],metalness:0,roughness:.72,glass:true,opacity:.48},
];

const materialName=(material)=>material.userData.vreelOriginalName||material.name;
const group=(label,materials,options,initial,target=()=>true)=>({label,materials,options,initial,target});
const configs={
  sofa:{title:'Lounge Duo',file:asset('sofa/model/Sofa.glb'),download:'VREEL_Lounge_Duo.glb',groups:{leather:group('Deri Yüzeyi',['Sofa_Fills_Leather_Black'],leather,'black-matte')}},
  chair:{title:'Aura Yönetici Koltuğu',file:asset('chair/model/Chair.glb'),download:'VREEL_Aura_Yonetici_Koltugu.glb',groups:{
    leather:group('Deri Yüzeyi',['Material__2147483027'],leather,'black-matte'),
    wood:group('Ahşap Detay',['WD'],wood,'original'),
    metal:group('Metal Detay',['MetalBlackMatte'],metal,'black'),
  }},
  desk:{title:'Axis Executive Desk',file:asset('desk/model/Desk.glb'),download:'VREEL_Axis_Executive_Desk.glb',groups:{
    desktop:group('Masa Üstü ve Ahşap Ayaklar',['Material__2147483063'],[...wood,...solids],'original',node=>/^Top/.test(node.name)||/^Leg/.test(node.name)),
    cabinet:group('Keson Gövdesi',['Material__2147482989'],wood,'original',node=>node.name==='KesonUnitBody'),
    cabinetFace:group('Keson Kapakları',['MDFBlack'],[...wood,...solids],'anthracite',node=>node.name==='KesonUnitFaces'),
    frontPanel:group('Ön Panel',['Material__2147483063'],[...wood,...solids,...glass],'original',node=>node.name.startsWith('FrontPanel')),
    metal:group('Metal Ayaklar',['MetalBlackMatte'],metal,'black'),
  }},
};
const config=configs[page];
const state=Object.fromEntries(Object.entries(config.groups).map(([key,value])=>[key,value.initial]));
const textures=new Map();let modelBlob=null,pointerStart=null,wheelGroup=null,wheelObject=null,wheelPage=0,pdfDocument=null;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const choice=(key,id=state[key])=>config.groups[key].options.find(option=>option.id===id);
const swatch=option=>option.image?`background-image:url('${option.image}')`:`background-color:${option.color}`;

function isolateMaterials(){viewer.model.root.traverse(node=>{if(!node.isMesh)return;const list=[node.material].flat().map(material=>{
  const clone=material.clone();clone.name=material.name;clone.userData.vreelOriginalName=material.name;clone.userData.vreelOriginal={map:material.map,color:material.color.clone(),metalness:material.metalness,roughness:material.roughness,transparent:material.transparent,opacity:material.opacity,depthWrite:material.depthWrite};return clone;
});node.material=Array.isArray(node.material)?list:list[0];});}
async function loadTexture(url,original){if(!textures.has(url))textures.set(url,viewer.createTexture(url));const base=await textures.get(url),texture=base.clone();if(original?.map){texture.offset.copy(original.map.offset);texture.repeat.copy(original.map.repeat);texture.center.copy(original.map.center);texture.rotation=original.map.rotation;texture.wrapS=original.map.wrapS;texture.wrapT=original.map.wrapT;}texture.needsUpdate=true;return texture;}
function targetMaterials(node,key){const spec=config.groups[key];if(!node.isMesh||!spec.target(node))return[];return [node.material].flat().filter(material=>spec.materials.includes(materialName(material)));}
async function paint(node,key,option){for(const material of targetMaterials(node,key)){const original=material.userData.vreelOriginal;if(option.original){material.map=original.map;material.color.copy(original.color);material.metalness=original.metalness;material.roughness=original.roughness;material.transparent=original.transparent;material.opacity=original.opacity;material.depthWrite=original.depthWrite;}else{material.map=option.image?await loadTexture(option.image,original):null;material.color.setRGB(...(option.factor||[1,1,1]));material.metalness=option.metalness??0;material.roughness=option.roughness??.55;material.transparent=Boolean(option.glass);material.opacity=option.opacity??1;material.depthWrite=!option.glass;}material.needsUpdate=true;}}
async function applyGroup(key,option=choice(key),single=null){const jobs=[];(single?[single]:[viewer.model.root]).forEach(root=>root.traverse?root.traverse(node=>jobs.push(paint(node,key,option))):jobs.push(paint(root,key,option)));await Promise.all(jobs);viewer.requestUpdate();}
function buildMaterials(){ui.groups.replaceChildren();ui.details.replaceChildren();for(const [key,spec] of Object.entries(config.groups)){const card=document.createElement('details');card.className='option-card';card.dataset.group=key;card.open=key===Object.keys(config.groups)[0];card.innerHTML=`<summary><span>${esc(spec.label)}</span><b data-summary="${key}"></b></summary><div class="option-body swatches">${spec.options.map(option=>`<button type="button" class="swatch" data-material="${key}" data-value="${option.id}" aria-label="${esc(option.label)}"><i style="${swatch(option)}"></i><span>${esc(option.label)}</span></button>`).join('')}</div>`;ui.groups.append(card);const row=document.createElement('div');row.innerHTML=`<dt>${esc(spec.label)}</dt><dd data-detail="${key}"></dd>`;ui.details.append(row);}ui.groups.addEventListener('click',event=>{const button=event.target.closest('[data-material]');if(button)select(button.dataset.material,button.dataset.value);});updateText();}
function updateText(){ui.selection.textContent=Object.entries(config.groups).map(([key,spec])=>`${spec.label}: ${choice(key).label}`).join(' · ');for(const key of Object.keys(config.groups)){document.querySelectorAll(`[data-summary="${key}"],[data-detail="${key}"]`).forEach(node=>node.textContent=choice(key).label);document.querySelectorAll(`[data-material="${key}"]`).forEach(node=>node.classList.toggle('active',node.dataset.value===state[key]));}}
function select(key,id){state[key]=id;updateText();applyGroup(key);if(wheelGroup===key)renderWheel();}

function addVariantCard(title,options,initial,onChange){const card=document.createElement('details');card.className='option-card';card.open=true;card.innerHTML=`<summary><span>${title}</span><b>${options.find(x=>x.id===initial).label}</b></summary><div class="option-body variant-options">${options.map(x=>`<button type="button" data-variant="${x.id}" class="${x.id===initial?'active':''}">${x.label}</button>`).join('')}</div>`;ui.groups.prepend(card);card.addEventListener('click',event=>{const button=event.target.closest('[data-variant]');if(!button)return;card.querySelectorAll('[data-variant]').forEach(x=>x.classList.toggle('active',x===button));card.querySelector('summary b').textContent=options.find(x=>x.id===button.dataset.variant).label;onChange(button.dataset.variant);});}
function setupSofa(){const wrappers=viewer.model.root.children.filter(wrapper=>wrapper.children.some(child=>child.isMesh));const tag=wrappers.find(wrapper=>wrapper.children.some(child=>child.name.toLowerCase().includes('tag')));const units=wrappers.filter(wrapper=>wrapper!==tag).sort((a,b)=>a.position.x-b.position.x);const clusters=[];for(const wrapper of units){let cluster=clusters.find(x=>Math.abs(x.x-wrapper.position.x)<.08);if(!cluster){cluster={x:wrapper.position.x,nodes:[]};clusters.push(cluster);}cluster.nodes.push(wrapper);}const apply=count=>{clusters.forEach((cluster,index)=>cluster.nodes.forEach(node=>node.visible=index<count));if(tag)tag.visible=true;viewer.reframe();};addVariantCard('Modül Sayısı',[{id:'one',label:'Tekli'},{id:'two',label:'İkili'},{id:'three',label:'Üçlü'}],'two',id=>apply({one:1,two:2,three:3}[id]));apply(2);}
function setupDesk(){const find=name=>viewer.findObjects(name);const wrappers=names=>names.flatMap(find).map(node=>node.parent);const stretch={160:['TopStretch002','FrontPanelStretch002'],200:['TopStretch','FrontPanelStretch'],240:['TopStretch001','FrontPanelStretch001']};const left=wrappers(['TopLeft','FrontPanelLeft','LegLeft']);const baseX=new Map(left.map(node=>[node,node.position.x]));const setSize=size=>{Object.entries(stretch).forEach(([key,names])=>wrappers(names).forEach(node=>node.visible=key===size));const offset=size==='160'?.4:size==='240'?-.4:0;left.forEach(node=>node.position.x=baseX.get(node)+offset);viewer.reframe();};addVariantCard('Masa Ölçüsü',[{id:'160',label:'160 cm'},{id:'200',label:'200 cm'},{id:'240',label:'240 cm'}],'200',setSize);setSize('200');
  const legs={left:find('LegLeft')[0]?.parent,right:find('LegRight')[0]?.parent};const kesonBodies=find('KesonUnitBody').map(x=>x.parent),kesonFaces=find('KesonUnitFaces').map(x=>x.parent);const setLayout=id=>{legs.left.visible=id!=='storage-left';legs.right.visible=id!=='storage-right';kesonBodies.forEach((node,index)=>node.visible=(id==='storage-left'?index===0:id==='storage-right'?index===1:false));kesonFaces.forEach((node,index)=>node.visible=(id==='storage-left'?index===0:id==='storage-right'?index===1:false));viewer.reframe();};addVariantCard('Ayak / Keson Düzeni',[{id:'storage-right',label:'Keson Sağda'},{id:'storage-left',label:'Keson Solda'},{id:'two-legs',label:'İki Metal Ayak'}],'storage-right',setLayout);setLayout('storage-right');}

function inferGroup(object,material){return Object.keys(config.groups).find(key=>targetMaterials(object,key).includes(material.raw))||Object.keys(config.groups).find(key=>config.groups[key].materials.includes(materialName(material.raw))&&config.groups[key].target(object));}
function renderWheel(){const spec=config.groups[wheelGroup],pages=Math.ceil(spec.options.length/8);wheelPage=Math.min(wheelPage,pages-1);const options=spec.options.slice(wheelPage*8,wheelPage*8+8);ui.wheelOptions.innerHTML='';options.forEach((option,index)=>{const theta=(-90+360*index/options.length)*Math.PI/180,button=document.createElement('button');button.className='wheel-swatch';button.style.setProperty('--x',`${Math.cos(theta)*105}px`);button.style.setProperty('--y',`${Math.sin(theta)*105}px`);button.style.cssText+=`;${swatch(option)}`;button.dataset.value=option.id;button.title=option.label;ui.wheelOptions.append(button);});document.querySelector('#wheel-title').textContent=spec.label;document.querySelector('#wheel-current').textContent=choice(wheelGroup).label;ui.wheel.querySelector('.wheel-pages').hidden=pages<2;document.querySelector('#wheel-page').textContent=`${wheelPage+1} / ${pages}`;}
function closeWheel(){ui.wheel.hidden=true;wheelGroup=null;wheelObject=null;}
function openWheel(key,object,x,y){wheelGroup=key;wheelObject=object;wheelPage=0;const box=ui.wheel.parentElement.getBoundingClientRect(),radius=145;ui.wheel.style.left=`${Math.max(radius,Math.min(x-box.left,box.width-radius))}px`;ui.wheel.style.top=`${Math.max(radius+25,Math.min(y-box.top,box.height-radius-30))}px`;ui.wheel.hidden=false;renderWheel();}
ui.wheelOptions.addEventListener('click',event=>{const button=event.target.closest('[data-value]');if(button&&wheelGroup&&wheelObject)paint(wheelObject,wheelGroup,choice(wheelGroup,button.dataset.value)).then(()=>viewer.requestUpdate());});
ui.wheel.querySelector('#wheel-close').addEventListener('click',closeWheel);document.querySelector('#wheel-prev').addEventListener('click',()=>{wheelPage--;renderWheel();});document.querySelector('#wheel-next').addEventListener('click',()=>{wheelPage++;renderWheel();});
viewer.addEventListener('pointerdown',event=>pointerStart={x:event.clientX,y:event.clientY});viewer.addEventListener('pointerup',event=>{if(!pointerStart||Math.hypot(event.clientX-pointerStart.x,event.clientY-pointerStart.y)>7)return;const hit=viewer.materialFromPoint(event.clientX,event.clientY);const key=hit&&inferGroup(hit.object,hit);if(key)openWheel(key,hit.object,event.clientX,event.clientY);else closeWheel();});

viewer.addEventListener('load',async()=>{document.querySelector('#model-loading').hidden=true;isolateMaterials();if(page==='sofa')setupSofa();if(page==='desk')setupDesk();for(const key of Object.keys(config.groups))await applyGroup(key);updateText();ui.notice.textContent='';});
viewer.addEventListener('error',()=>{ui.notice.textContent='3D model yüklenemedi. Lütfen sayfayı yenileyin.';});viewer.addEventListener('progress',event=>{const bar=viewer.querySelector('.progress'),span=bar?.querySelector('span');if(span)span.style.width=`${event.detail.totalProgress*100}%`;if(bar)bar.hidden=event.detail.totalProgress===1;});
async function load(){ui.notice.textContent='3D model yükleniyor…';const response=await fetch(config.file);if(!response.ok)throw new Error(response.status);modelBlob=await response.blob();viewer.src=URL.createObjectURL(modelBlob);}load().catch(error=>{console.error(error);ui.notice.textContent='3D model yüklenemedi.';});

const studio={environment:'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/brown_photostudio_02_1k.hdr',exposure:1.12,shadow:1.35,softness:.72};viewer.environmentImage=studio.environment;viewer.exposure=studio.exposure;viewer.shadowIntensity=studio.shadow;viewer.shadowSoftness=studio.softness;viewer.setRotationSpeed(40);
const activate=(selector,current)=>document.querySelectorAll(selector).forEach(node=>node.classList.toggle('active',node===current));
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{activate('.tab',button);document.querySelectorAll('.tab-panel').forEach(panel=>panel.classList.toggle('active',panel.id===button.dataset.tab));}));
document.querySelector('[data-action="rotate"]').addEventListener('click',event=>{const on=event.currentTarget.getAttribute('aria-pressed')!=='true';viewer.setAutoRotate(on);event.currentTarget.setAttribute('aria-pressed',on);});document.querySelector('#rotation-speed').addEventListener('input',event=>{viewer.setRotationSpeed(event.target.value);event.target.nextElementSibling.value=`${event.target.value}°/sn`;});
document.querySelectorAll('[data-lighting]').forEach(button=>button.addEventListener('click',()=>{viewer.lightingPreset=button.dataset.lighting;document.querySelectorAll('[data-lighting]').forEach(node=>node.setAttribute('aria-pressed',node===button));}));const lighting=document.querySelector('.lighting-presets');document.querySelector('[data-action="lighting-menu"]').addEventListener('click',()=>lighting.hidden=!lighting.hidden);
document.querySelector('[data-action="fullscreen"]').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():viewer.parentElement.requestFullscreen());document.querySelector('[data-action="reset"]').addEventListener('click',()=>viewer.reframe());document.querySelector('[data-action="zoom-in"]').addEventListener('click',()=>{const o=viewer.getCameraOrbit();viewer.cameraOrbit=`${o.theta}rad ${o.phi}rad ${o.radius*.82}m`;});document.querySelector('[data-action="zoom-out"]').addEventListener('click',()=>{const o=viewer.getCameraOrbit();viewer.cameraOrbit=`${o.theta}rad ${o.phi}rad ${o.radius*1.22}m`;});document.querySelector('[data-action="pan-left"]').addEventListener('click',()=>viewer.panView(-1));document.querySelector('[data-action="pan-right"]').addEventListener('click',()=>viewer.panView(1));document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{const views={front:'0deg 75deg auto',side:'90deg 75deg auto',top:'0deg 10deg auto'};viewer.cameraOrbit=views[button.dataset.view];activate('[data-view]',button);}));
document.querySelector('[data-action="snapshot"]').addEventListener('click',()=>{const link=document.createElement('a');link.href=viewer.toDataURL();link.download=config.download.replace('.glb','.png');link.click();});document.querySelector('[data-action="snapshot-4k"]').addEventListener('click',()=>{const link=document.createElement('a');link.href=viewer.to4KDataURL();link.download=config.download.replace('.glb','_4K.png');link.click();});document.querySelector('[data-action="dimensions"]').addEventListener('click',event=>{const box=document.querySelector('#dimensions-overlay'),dims=viewer.getDimensions();box.hidden=!box.hidden;box.innerHTML=box.hidden?'':`<span>G ${Math.round(dims.x)} cm</span><span>Y ${Math.round(dims.y)} cm</span><span>D ${Math.round(dims.z)} cm</span>`;event.currentTarget.setAttribute('aria-pressed',!box.hidden);});
document.querySelector('#reset-materials').addEventListener('click',()=>{for(const [key,spec] of Object.entries(config.groups)){state[key]=spec.initial;applyGroup(key);}updateText();});document.querySelector('#source-download').addEventListener('click',()=>{if(!modelBlob)return;const link=document.createElement('a');link.href=URL.createObjectURL(modelBlob);link.download=config.download;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),60000);});
document.querySelector('#datasheet').addEventListener('click',()=>{try{const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'}),image=viewer.toDataURL();pdf.setFillColor(15,27,45);pdf.rect(0,0,210,28,'F');pdf.setTextColor(255,255,255);pdf.setFontSize(20);pdf.text('VREEL',16,18);pdf.setTextColor(15,27,45);pdf.setFontSize(20);pdf.text(config.title,16,44);pdf.addImage(image,'PNG',16,54,178,100,undefined,'FAST');pdf.setFontSize(10);let y=166;for(const [key,spec] of Object.entries(config.groups)){pdf.text(`${spec.label}: ${choice(key).label}`,16,y);y+=7;}pdfDocument=pdf;document.querySelector('#pdf-preview').innerHTML=`<img src="${image}" alt="${esc(config.title)} teknik föy önizlemesi">`;document.querySelector('#pdf-modal').hidden=false;}catch(error){console.error(error);ui.notice.textContent='PDF teknik föyü oluşturulamadı.';}});document.querySelector('#download-pdf').addEventListener('click',()=>pdfDocument?.save(config.download.replace('.glb','.pdf')));document.querySelector('#pdf-modal .modal-close').addEventListener('click',()=>document.querySelector('#pdf-modal').hidden=true);document.querySelector('#add').addEventListener('click',()=>document.querySelector('#order-modal').hidden=false);document.querySelector('[data-close-order]').addEventListener('click',()=>document.querySelector('#order-modal').hidden=true);document.querySelector('#order-form').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#order-status').textContent='Talep gönderilmedi: sipariş alıcısı henüz bağlı değil.';});
buildMaterials();
